version: '3.8'

services:   
  trucks-test-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: trucks-test-db

    ports:
      - "1433:1433"

    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD:-"Passw0rd(!)"}
      - MSSQL_SA_PASSWORD=${DB_PASSWORD:-"Passw0rd(!)"}

    volumes:
      - sql-server-volume:/var/opt/mssql
      - ./server-init.sh:/server-init.sh
      - ./db-init.sh:/db-init.sh
      - ./db-init.sql:/db-init.sql

    command: /bin/bash server-init.sh

volumes: 
  sql-server-volume:        
    driver: local